# Generated by Django 3.2.25 on 2024-05-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KioskCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer', models.CharField(max_length=100)),
                ('reams_used', models.FloatField()),
                ('issues', models.CharField(max_length=100)),
                ('toner_status', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('ricoh_ticket', models.CharField(max_length=100)),
                ('servicenow_ticket', models.CharField(max_length=100)),
            ],
        ),
    ]
