# Generated by Django 3.2.25 on 2024-06-04 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer', models.CharField(max_length=100)),
                ('reams_used', models.IntegerField()),
                ('issues', models.CharField(max_length=100)),
                ('toner_status', models.CharField(max_length=50)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('ricoh_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('servicenow_ticket', models.CharField(blank=True, max_length=50, null=True)),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('charging_station', models.CharField(blank=True, max_length=100, null=True)),
                ('computer', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
