# Generated by Django 3.2.25 on 2024-05-23 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kioskApp', '0002_kioskcheck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskcheck',
            name='completed_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kioskcheck',
            name='issue_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kioskcheck',
            name='reams_used',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kioskcheck',
            name='ricoh_ticket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kioskcheck',
            name='servicenow_ticket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kioskcheck',
            name='toner_status',
            field=models.CharField(max_length=50),
        ),
    ]
