# Generated by Django 3.2.25 on 2024-06-07 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kioskApp', '0004_remove_kioskcheck_charging_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('location1', 'Location 1'), ('location2', 'Location 2'), ('location3', 'Location 3'), ('location4', 'Location 4'), ('location5', 'Location 5'), ('location6', 'Location 6'), ('location7', 'Location 7'), ('location8', 'Location 8'), ('location9', 'Location 9'), ('location10', 'Location 10'), ('location11', 'Location 11'), ('location12', 'Location 12'), ('location13', 'Location 13')], max_length=50)),
                ('issue_description', models.TextField()),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
