# Generated by Django 3.2.25 on 2024-06-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskApp', '0006_chargingstationcheck_servicenow_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskcheck',
            name='computer_issue',
            field=models.CharField(blank=True, choices=[('missing_items', 'Missing items'), ('network', 'Network'), ('display_issue', 'Display issue'), ('all_good', 'All good'), ('unresponsive', 'Unresponsive')], max_length=20, null=True),
        ),
    ]
