# Generated by Django 3.2.25 on 2024-06-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskApp', '0008_auto_20240609_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstationcheck',
            name='charger_status',
            field=models.CharField(choices=[('', '--Please choose an option--'), ('no_issues', 'No issues found'), ('no_charge', 'Does not charge'), ('cable-malfunction', 'Cable malfunction'), ('test', 'Test')], max_length=50),
        ),
    ]
