# Generated by Django 3.2.25 on 2024-06-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kioskApp', '0010_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
